
services:
    frontend:
        image: hello-frontend:v2 # The later version with env-vars
        ports:
            - "5000:5000"
        
    backend:
        image: hello-backend:v2 # Same as above
        environment:
            REDIS_HOST: "redis" # Adding this as this is not in v2-image
        ports:
            - "8080:8080"
        restart: unless-stopped

    redis:
        image: redis

